### ISSUE TITLE
cordova-fetch patch release August 2018

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-fetch#37]
Migrated from <https://issues.apache.org/jira/browse/CB-14251>, with minor updates:

_`1.3.x` patch release_ wanted with the following updates:
 * repo URL fix from GH-20
 * explicit requirement for cordova-common@2.2.5 (or cordova-common@^2.2.5) in dependencies, which would be an in-range update (not wanted in `master` branch, see note below)
 * _resolve coho audit-license-headers issue in `1.3.x` patch release branch (cherry-pick of some commits from GH-36) ref: GH-35_

Following steps at <https://github.com/apache/cordova-coho/blob/master/docs/tools-release-process.md> (with some minor adjustments)

Note: cordova-common@^2.2.5 dependency update is not wanted in `master` branch. The master branch of this and other Cordova repos should now target the next major release as discussed in [this dev@cordova.apache.org thread](https://lists.apache.org/thread.html/083ffe568bad2a8adc5533cbe5aca481bdd921e22a6aad9602aaded2@%3Cdev.cordova.apache.org%3E).

**Comment by raphinesse** [comment]
Closing, as 1.3.1 has been released.
