### ISSUE TITLE
Support node recursive module resolution algorithm

### ISSUE THREAD

**Issue by ariofrio** [apache/cordova-fetch#43]
Currently, cordova-fetch only checks the project's node_module directory, without checking parent directories. For example, in:

```
myproject/
  node_modules/
    dependency/ -> ../packages/dependency
  packages/
    dependency/
    subproject/
      index.js
      config.xml
      package.json
  package.json
```

If we `require('dependency')` from index.js, node will search through all ancestor directories for node_modules/dependency.

However, `cordova-fetch` doesn't support this. Instead, it will install `dependency` again (from the npm repository) inside myproject/packages/subproject/node_modules

This is a problem for use cases like yarn workspaces, where the *standard* node module resolution algorithm is used to help "dependency" be developed alongside "subproject".

Solving this problem could be a good way to improve support for yarn workspaces without needing to [add explicit support for yarn](https://github.com/apache/cordova-cli/pull/292#issuecomment-401331607).

### References:

- [resolve package](https://www.npmjs.com/package/resolve) - aims to implement node's algorithm fully, could be used as an alternative to get-installed-path
- the [node module resolution algorithm](https://nodejs.org/api/modules.html#modules_all_together)

**Comment by raphinesse** [comment]
Thanks for bringing this to our attention. I think we should try to support the full module resolution. Either using the package you linked to or https://github.com/sindresorhus/resolve-from.

If the resolved module path does not satisfy the spec, I'd just stop there and continue with installing the requested version. Alternatively we could try searching upwards for the correct version, but I'd rather stick to node's plain module resolution. I can't imagine any use cases that would benefit from doing more than require can do. What do you think?

**Comment by ariofrio** [comment]
Yeah, I think that doing what require does, not more or less, is the most useful behavior.
