### ISSUE TITLE
Install a cordova plugin by tagged version from a custom git repo fails

### ISSUE THREAD

**Issue by duydao** [apache/cordova-fetch#54]
We're having trouble installing plugins from a private git repository by url.

`cordova plugin --verbose add git+https://gitlab.internal/cordova-plugin-our-custom-plugin.git`

Adding an existing tag to the url to make cordova-fetch fail:
`cordova plugin --verbose add git+https://gitlab.internal/cordova-plugin-our-custom-plugin.git#1.11.0`

The error implies, that the destination path could not be found:

```
Failed to get absolute path to installed module
    at C:\Users\xyz\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\fetch.js:173:37
```
Since `--nofetch` is deprecated in recent versions of cordova, is there a way to make this work?

**Comment by duydao** [comment]
It works if the module is not installed in node_modules yet

**Comment by raphinesse** [comment]
The error `Failed to get absolute path to installed module` has only been used in version 1 of this module. I'm afraid we can't support that anymore. Please update to a more recent version of Cordova. The issue you are describing should be fixed by that.
