### ISSUE TITLE
Adding Cordova plugins is much slower

### ISSUE THREAD

**Issue by chrisjdev** [apache/cordova-fetch#55]
I've been looking at why our builds for an Ionic based application are much slower with Cordova 8.1.2 vs 6.5, and I believe it's related to this project. For example, adding a plugin via link where it doesn't actually need to download anything, in our project, Cordova 6.5 takes 3.6s, and 8.1 takes 9.5s. As I dug into the code further, I found that dependency-ls takes ~3.5s, and it runs before and after npm install in cordova-fetch. With our 29 plugins, this adds a solid 3 minutes. It's unfortunately even slower with our jenkins VM, adding ~6 minutes to builds. I realize this is called out as a quirk in this proposal: https://github.com/apache/cordova-discuss/blob/master/proposals/fetching.md . I wonder if this quirk could be addressed to get the package.name in less than 7 seconds.

**Comment by dpogue** [comment]
This has been addressed in master and will be fixed in the next major version release of cordova-fetch.
