### ISSUE TITLE
cordova-fetch cannot install plugins from git repos with npm 3 if project has unmet peer dependencies

### ISSUE THREAD

**Issue by NateEag** [apache/cordova-fetch#66]
# Bug Report

As the subject line says, the `cordova-fetch` module cannot install plugins from git repositories when used with npm 3 (and perhaps 4 - I haven't tested that).

## Problem

When I run `cordova plugin add --save git+https://github.com/apache/cordova-plugin-inappbrowser.git`, I get an error message instead of the plugin installing correctly (this happens with every git repository I've tested).

### What is expected to happen?

I expect the plugin to install correctly.

### What does actually happen?

I see the following error output:

```
Failed to fetch plugin git+https://github.com/apache/cordova-plugin-inappbrowser.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: Cannot find module 'UNMET/package.json' from '/Users/neagleson/cordova-fetch-bug-demo/test'
```

## Information

The problematic code is [here](https://github.com/apache/cordova-fetch/blob/d2be9307f31ae8981aa451e91904febb081bce43/index.js#L99). It assumes that the last line of output will have the installed plugin's spec on it, but that is not true when there is an unmet peer dependency - hence the `'UNMET'` string in the error message.

### Command or Code

Here is a script that reliably reproduces the problem on my machine (Mac OS X 10.14.6). It assumes a working `node` and `npm` version of some sort are already installed.

```bash
#! /bin/bash

mkdir -p "$HOME/cordova-fetch-bug-demo"

cd "$HOME/cordova-fetch-bug-demo"

# Accept all default options when prompted
npm init

npm install --save cordova@9.0.0
npm install --save npm@3.10.3

export PATH="$HOME/cordova-fetch-bug-demo/node_modules/.bin:$PATH"

cordova create test com.example.cordovafetchbug CordovaFetchBug

cd test

cordova platform add ios

# Adding a dependency that has an unmet peer dependency to trigger the issue
npm install --save s3-sync-aws@1.1.0

cordova plugin add --save git+https://github.com/apache/cordova-plugin-inappbrowser.git
```

### Version information

As documented above, Cordova CLI 9, default version of the iOS platform, installing the cordova-inapp-browser plugin from Git, XCode 10.1, on Mac OS X 10.14.6.

## Checklist

- [X] I searched for existing GitHub issues
- [X] I updated all Cordova tooling to most recent version
- [X] I included all the necessary information above

**Comment by misterti** [comment]
Do we have a workaround, or at least how can i see the underlying error, what is the unmet dependency?
Thanks

**Comment by breautek** [comment]
> or at least how can i see the underlying error

Attaching `--verbose` flag to any cordova command should spit out a lot of potentially useful debug information, including information from stdout of spawned processes.

Also a side note that support for NPM 3 is ending in the next major, which is already committed to master. So if there are any issues regarding NPM 3, it will likely be no longer addressed. You should consider upgrading if possible.

**Comment by NateEag** [comment]
In my project I actually wound up removing the plugin that caused the error for unrelated reasons.

@breautek Thanks for the heads-up about npm 3. If you look at the [code in question](https://github.com/apache/cordova-fetch/blob/d2be9307f31ae8981aa451e91904febb081bce43/index.js#L99), you'll see a comment claiming that it also applies with npm 4.

As I said above, I haven't tested that, but it seems likely to me this bug will exist there too.

**Comment by misterti** [comment]
Verbose still doesn't give any usable information. I get module_not_found from async.js and then unmet\package.json at the end. Can i get even more verbose output from each step of cordova plugin add?

**Comment by raphinesse** [comment]
@NateEag Actually we drop support for `npm@<5` in the next major. The code you referenced has already been removed in #80.

@misterti No, unfortunately there's no built-in way of getting even more verbose output. You could patch the version of `cordova-fetch` used by your `cordova` installation to log `npmInstallOutput` here: https://github.com/apache/cordova-fetch/blob/d2be9307f31ae8981aa451e91904febb081bce43/index.js#L93-L94

Or maybe you could just try installing what you are trying to install using `npm install` then you should be seeing any _unmet dependency_ warnings.

**Comment by NateEag** [comment]
@raphinesse Gotcha, thanks. Good to know.

**Comment by misterti** [comment]
@raphinesse thanks, that worked perfectly. I dumped the npmInstallOutput and got all the info i needed. Doing npm install did not fail. I think a step after failed.

`console.log(dump(npmInstallOutput));`
where dump() is a copy from http://www.openjs.com/scripts/others/dump_function_php_print_r.php

**Comment by breautek** [comment]
> Sorry for code formatting, it just won't work

For future reference, you can do block-level formatting by using 3 backticks ( ``` ) followed by a new line, using another 3 backticks on a new line to end the block.

**Comment by erisu** [comment]
I am closing out this ticket as we do not support npm 3.
