### ISSUE TITLE
CordovaError: Could not determine package name from output

### ISSUE THREAD

**Issue by markarupert** [apache/cordova-fetch#67]
# Bug Report
    
## Problem
When I attempt to install a plugin I get an error.

These are all steps I have done successfully in the past.

### What is expected to happen?
Successful installation of the plugin

### What does actually happen?
$ cordova plugin add ../cordova-background-geolocation
{ CordovaError: Could not determine package name from output:
up to date in 10.929s
    at getTargetPackageSpecFromNpmInstallOutput (/usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/index.js:104:11)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
  name: 'CordovaError',
  message:
   'Could not determine package name from output:\nup to date in 10.929s',
  code: 0,
  context: undefined }

### Environment, Platform, Device

Mac 10.14.4

### Version information

Device manufacturer / model:
Cordova version (cordova -v):
9.0.0 (cordova-lib@9.0.1)
Cordova platform version (cordova platform ls):
android ^8.0.0
browser ^6.0.0
electron ^1.0.0
osx ^5.0.0
windows ^7.0.0

## Checklist

- [ x] I searched for existing GitHub issues
- [ x] I updated all Cordova tooling to most recent version
- [ x] I included all the necessary information above

**Comment by breautek** [comment]
Does it work if you prefix your filepath with `file:` like below?

`cordova plugin add file:../cordova-background-geolocation`

**Comment by markarupert** [comment]
I ended up wiping the platform and reloading all of the plugins and the ghost problem went away.

Thanks.

**Comment by HarshitChhipa** [comment]
JUST for knowledge, This occurs when there is a mismatch of the plugins name try to update or sync the plugin's name from package.json file.

**Comment by wayneburkett** [comment]
> JUST for knowledge, This occurs when there is a mismatch of the plugins name try to update or sync the plugin's name from package.json file.

Mismatch where? What two (or more) things are you referring to here that could be mismatched?

**Comment by ifredom** [comment]
How to solve this problem

**Comment by yogskumar** [comment]
hi @ifredom just use below command

1) npm uninstall -g cordova
2) npm install -g cordova

and let me know if you have any issue

**Comment by smallscript** [comment]
Uninstall and reinstall fixed my problem of this same kind.

**Comment by Wynand101** [comment]
I did a mixture of all the above comments with some additions:

- Remove all platforms (cordova platform rm android)
- Remove all plugins (Wrote a script for this that repeats "cordova plugin rm <plugin>" for all my plugins)
- Clean my config.xml and package.json files (Checked all dependencies and versions to point to correct cordova version, in my case cordova@11.1.0)
- Run "npm install"
- Add all my plugins back in (Wrote a script for this that repeats "cordova plugin add <plugin>" for all my plugins)
- Add Android platform back in (cordova platform add android@10.0.0)
- cordova run android
